/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036JobStepStepHet } from './dbv0036JobStepStepHet';
import { Dbv0036JobStepStepTask } from './dbv0036JobStepStepTask';
import { Dbv0036JobStepStepTres } from './dbv0036JobStepStepTres';

/**
* Step details
*/
export class Dbv0036JobStepStep {
    /**
    * Parent job id
    */
    'jobId'?: number;
    'het'?: Dbv0036JobStepStepHet;
    /**
    * Step id
    */
    'id'?: string;
    /**
    * Step name
    */
    'name'?: string;
    'task'?: Dbv0036JobStepStepTask;
    'tres'?: Dbv0036JobStepStepTres;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "number"
        },
        {
            "name": "het",
            "baseName": "het",
            "type": "Dbv0036JobStepStepHet"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "task",
            "baseName": "task",
            "type": "Dbv0036JobStepStepTask"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "Dbv0036JobStepStepTres"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobStepStep.attributeTypeMap;
    }
}

