/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0037JobStepStepTresRequested } from './dbv0037JobStepStepTresRequested';

/**
* TRES usage
*/
export class Dbv0037JobStepStepTres {
    'requested'?: Dbv0037JobStepStepTresRequested;
    'consumed'?: Dbv0037JobStepStepTresRequested;
    /**
    * TRES list of attributes
    */
    'allocated'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requested",
            "baseName": "requested",
            "type": "Dbv0037JobStepStepTresRequested"
        },
        {
            "name": "consumed",
            "baseName": "consumed",
            "type": "Dbv0037JobStepStepTresRequested"
        },
        {
            "name": "allocated",
            "baseName": "allocated",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037JobStepStepTres.attributeTypeMap;
    }
}

