/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036QosLimitsMaxTresMinutesPer } from './dbv0036QosLimitsMaxTresMinutesPer';

/**
* Max TRES minutes settings
*/
export class Dbv0036QosLimitsMaxTresMinutes {
    'per'?: Dbv0036QosLimitsMaxTresMinutesPer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "per",
            "baseName": "per",
            "type": "Dbv0036QosLimitsMaxTresMinutesPer"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosLimitsMaxTresMinutes.attributeTypeMap;
    }
}

