/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Node details
*/
export class Dbv0036JobStepNodes {
    /**
    * Total number of nodes in step
    */
    'count'?: number;
    /**
    * Nodes in step
    */
    'range'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobStepNodes.attributeTypeMap;
    }
}

