/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036DiagTime } from './dbv0036DiagTime';

/**
* Statistics by RPC type
*/
export class Dbv0036DiagRPCs {
    /**
    * RPC type
    */
    'rpc'?: string;
    /**
    * Number of RPCs
    */
    'count'?: number;
    'time'?: Dbv0036DiagTime;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rpc",
            "baseName": "rpc",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "Dbv0036DiagTime"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036DiagRPCs.attributeTypeMap;
    }
}

