/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036AssociationDefault } from './dbv0036AssociationDefault';
import { Dbv0036AssociationMax } from './dbv0036AssociationMax';
import { Dbv0036AssociationMin } from './dbv0036AssociationMin';
import { Dbv0036AssociationUsage } from './dbv0036AssociationUsage';

/**
* Association description
*/
export class Dbv0036Association {
    /**
    * Assigned account
    */
    'account'?: string;
    /**
    * Assigned cluster
    */
    'cluster'?: string;
    '_default'?: Dbv0036AssociationDefault;
    /**
    * List of properties of association
    */
    'flags'?: Array<string>;
    'max'?: Dbv0036AssociationMax;
    'min'?: Dbv0036AssociationMin;
    /**
    * Parent account name
    */
    'parentAccount'?: string;
    /**
    * Assigned partition
    */
    'partition'?: string;
    /**
    * Assigned priority
    */
    'priority'?: number;
    /**
    * Assigned QOS
    */
    'qos'?: Array<string>;
    /**
    * Raw fairshare shares
    */
    'sharesRaw'?: number;
    'usage'?: Dbv0036AssociationUsage;
    /**
    * Assigned user
    */
    'user'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "Dbv0036AssociationDefault"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Array<string>"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "Dbv0036AssociationMax"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "Dbv0036AssociationMin"
        },
        {
            "name": "parentAccount",
            "baseName": "parent_account",
            "type": "string"
        },
        {
            "name": "partition",
            "baseName": "partition",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        },
        {
            "name": "qos",
            "baseName": "qos",
            "type": "Array<string>"
        },
        {
            "name": "sharesRaw",
            "baseName": "shares_raw",
            "type": "number"
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "Dbv0036AssociationUsage"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036Association.attributeTypeMap;
    }
}

