/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036JobStepCPURequestedFrequency } from './dbv0036JobStepCPURequestedFrequency';

/**
* CPU properties
*/
export class Dbv0036JobStepCPU {
    'requestedFrequency'?: Dbv0036JobStepCPURequestedFrequency;
    /**
    * CPU governor
    */
    'governor'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestedFrequency",
            "baseName": "requested_frequency",
            "type": "Dbv0036JobStepCPURequestedFrequency"
        },
        {
            "name": "governor",
            "baseName": "governor",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobStepCPU.attributeTypeMap;
    }
}

