/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036JobStepStatisticsCPU } from './dbv0036JobStepStatisticsCPU';
import { Dbv0036JobStepStatisticsEnergy } from './dbv0036JobStepStatisticsEnergy';

/**
* Statistics of job step
*/
export class Dbv0036JobStepStatistics {
    'cPU'?: Dbv0036JobStepStatisticsCPU;
    'energy'?: Dbv0036JobStepStatisticsEnergy;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cPU",
            "baseName": "CPU",
            "type": "Dbv0036JobStepStatisticsCPU"
        },
        {
            "name": "energy",
            "baseName": "energy",
            "type": "Dbv0036JobStepStatisticsEnergy"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobStepStatistics.attributeTypeMap;
    }
}

