/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* System time values
*/
export class Dbv0036JobTimeSystem {
    /**
    * Total number of CPU-seconds used by the system on behalf of the process (in kernel mode), in seconds
    */
    'seconds'?: number;
    /**
    * Total number of CPU-seconds used by the system on behalf of the process (in kernel mode), in microseconds
    */
    'microseconds'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "seconds",
            "baseName": "seconds",
            "type": "number"
        },
        {
            "name": "microseconds",
            "baseName": "microseconds",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobTimeSystem.attributeTypeMap;
    }
}

