/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036JobArrayLimits } from './dbv0036JobArrayLimits';

/**
* Array properties (optional)
*/
export class Dbv0036JobArray {
    /**
    * Job id of array
    */
    'jobId'?: number;
    'limits'?: Dbv0036JobArrayLimits;
    /**
    * Array task
    */
    'task'?: string;
    /**
    * Array task id
    */
    'taskId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "number"
        },
        {
            "name": "limits",
            "baseName": "limits",
            "type": "Dbv0036JobArrayLimits"
        },
        {
            "name": "task",
            "baseName": "task",
            "type": "string"
        },
        {
            "name": "taskId",
            "baseName": "task_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobArray.attributeTypeMap;
    }
}

