/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Reservation usage details
*/
export class Dbv0036JobReservation {
    /**
    * Database id of reservation
    */
    'id'?: number;
    /**
    * Name of reservation
    */
    'name'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobReservation.attributeTypeMap;
    }
}

