/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0037AssociationMaxTresMinutes } from './dbv0037AssociationMaxTresMinutes';
import { Dbv0037AssociationMaxTresPer } from './dbv0037AssociationMaxTresPer';

/**
* Max TRES settings
*/
export class Dbv0037AssociationMaxTres {
    'per'?: Dbv0037AssociationMaxTresPer;
    /**
    * TRES list of attributes
    */
    'total'?: Array<object>;
    'minutes'?: Dbv0037AssociationMaxTresMinutes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "per",
            "baseName": "per",
            "type": "Dbv0037AssociationMaxTresPer"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Array<object>"
        },
        {
            "name": "minutes",
            "baseName": "minutes",
            "type": "Dbv0037AssociationMaxTresMinutes"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037AssociationMaxTres.attributeTypeMap;
    }
}

