/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036AssociationShortInfo } from './dbv0036AssociationShortInfo';
import { Dbv0036JobArray } from './dbv0036JobArray';
import { Dbv0036JobComment } from './dbv0036JobComment';
import { Dbv0036JobExitCode } from './dbv0036JobExitCode';
import { Dbv0036JobHet } from './dbv0036JobHet';
import { Dbv0036JobMcs } from './dbv0036JobMcs';
import { Dbv0036JobRequired } from './dbv0036JobRequired';
import { Dbv0036JobReservation } from './dbv0036JobReservation';
import { Dbv0036JobState } from './dbv0036JobState';
import { Dbv0036JobStep } from './dbv0036JobStep';
import { Dbv0036JobTime } from './dbv0036JobTime';
import { Dbv0036JobTres } from './dbv0036JobTres';
import { Dbv0036JobWckey } from './dbv0036JobWckey';

/**
* Single job description
*/
export class Dbv0036Job {
    /**
    * Account charged by job
    */
    'account'?: string;
    'comment'?: Dbv0036JobComment;
    /**
    * Nodes allocated to job
    */
    'allocationNodes'?: string;
    'array'?: Dbv0036JobArray;
    'time'?: Dbv0036JobTime;
    'association'?: Dbv0036AssociationShortInfo;
    /**
    * Assigned cluster
    */
    'cluster'?: string;
    /**
    * Constraints on job
    */
    'constraints'?: string;
    'derivedExitCode'?: Dbv0036JobExitCode;
    'exitCode'?: Dbv0036JobExitCode;
    /**
    * List of properties of job
    */
    'flags'?: Array<string>;
    /**
    * User\'s group to run job
    */
    'group'?: string;
    'het'?: Dbv0036JobHet;
    /**
    * Job id
    */
    'jobId'?: number;
    /**
    * Assigned job name
    */
    'name'?: string;
    'mcs'?: Dbv0036JobMcs;
    /**
    * List of nodes allocated for job
    */
    'nodes'?: string;
    /**
    * Assigned job\'s partition
    */
    'partition'?: string;
    /**
    * Priority
    */
    'priority'?: number;
    /**
    * Assigned qos name
    */
    'qos'?: string;
    'required'?: Dbv0036JobRequired;
    /**
    * User who requested job killed
    */
    'killRequestUser'?: string;
    'reservation'?: Dbv0036JobReservation;
    'state'?: Dbv0036JobState;
    /**
    * Job step description
    */
    'steps'?: Array<Dbv0036JobStep>;
    'tres'?: Dbv0036JobTres;
    /**
    * Job user
    */
    'user'?: string;
    'wckey'?: Dbv0036JobWckey;
    /**
    * Directory where job was initially started
    */
    'workingDirectory'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "Dbv0036JobComment"
        },
        {
            "name": "allocationNodes",
            "baseName": "allocation_nodes",
            "type": "string"
        },
        {
            "name": "array",
            "baseName": "array",
            "type": "Dbv0036JobArray"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "Dbv0036JobTime"
        },
        {
            "name": "association",
            "baseName": "association",
            "type": "Dbv0036AssociationShortInfo"
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string"
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "string"
        },
        {
            "name": "derivedExitCode",
            "baseName": "derived_exit_code",
            "type": "Dbv0036JobExitCode"
        },
        {
            "name": "exitCode",
            "baseName": "exit_code",
            "type": "Dbv0036JobExitCode"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Array<string>"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string"
        },
        {
            "name": "het",
            "baseName": "het",
            "type": "Dbv0036JobHet"
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "mcs",
            "baseName": "mcs",
            "type": "Dbv0036JobMcs"
        },
        {
            "name": "nodes",
            "baseName": "nodes",
            "type": "string"
        },
        {
            "name": "partition",
            "baseName": "partition",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        },
        {
            "name": "qos",
            "baseName": "qos",
            "type": "string"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Dbv0036JobRequired"
        },
        {
            "name": "killRequestUser",
            "baseName": "kill_request_user",
            "type": "string"
        },
        {
            "name": "reservation",
            "baseName": "reservation",
            "type": "Dbv0036JobReservation"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "Dbv0036JobState"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<Dbv0036JobStep>"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "Dbv0036JobTres"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "wckey",
            "baseName": "wckey",
            "type": "Dbv0036JobWckey"
        },
        {
            "name": "workingDirectory",
            "baseName": "working_directory",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036Job.attributeTypeMap;
    }
}

