/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0037QosLimitsMaxTresMinutes } from './dbv0037QosLimitsMaxTresMinutes';
import { Dbv0037QosLimitsMaxTresPer } from './dbv0037QosLimitsMaxTresPer';

/**
* Limits on TRES
*/
export class Dbv0037QosLimitsMaxTres {
    'minutes'?: Dbv0037QosLimitsMaxTresMinutes;
    'per'?: Dbv0037QosLimitsMaxTresPer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minutes",
            "baseName": "minutes",
            "type": "Dbv0037QosLimitsMaxTresMinutes"
        },
        {
            "name": "per",
            "baseName": "per",
            "type": "Dbv0037QosLimitsMaxTresPer"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037QosLimitsMaxTres.attributeTypeMap;
    }
}

