/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0037QosLimitsMinTres } from './dbv0037QosLimitsMinTres';

/**
* Min limit settings
*/
export class Dbv0037QosLimitsMin {
    /**
    * Min priority threshold
    */
    'priorityThreshold'?: number;
    'tres'?: Dbv0037QosLimitsMinTres;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "priorityThreshold",
            "baseName": "priority_threshold",
            "type": "number"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "Dbv0037QosLimitsMinTres"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037QosLimitsMin.attributeTypeMap;
    }
}

