/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036QosLimitsMax } from './dbv0036QosLimitsMax';
import { Dbv0036QosLimitsMin } from './dbv0036QosLimitsMin';

/**
* Assigned limits
*/
export class Dbv0036QosLimits {
    'max'?: Dbv0036QosLimitsMax;
    'min'?: Dbv0036QosLimitsMin;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "max",
            "baseName": "max",
            "type": "Dbv0036QosLimitsMax"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "Dbv0036QosLimitsMin"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosLimits.attributeTypeMap;
    }
}

