/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036DiagTime1 } from './dbv0036DiagTime1';

/**
* Statistics by user RPCs
*/
export class Dbv0036DiagUsers {
    /**
    * User name
    */
    'user'?: string;
    /**
    * Number of RPCs
    */
    'count'?: number;
    'time'?: Dbv0036DiagTime1;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "Dbv0036DiagTime1"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036DiagUsers.attributeTypeMap;
    }
}

