/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Dbv0036CoordinatorInfo {
    /**
    * Name of user
    */
    'name'?: string;
    /**
    * If user is coordinator of this account directly or coordinator status was inheirted from a higher account in the tree
    */
    'direct'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "direct",
            "baseName": "direct",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036CoordinatorInfo.attributeTypeMap;
    }
}

