/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* TRES requested for job
*/
export class Dbv0037JobStepStepTresRequested {
    /**
    * TRES list of attributes
    */
    'average'?: Array<object>;
    /**
    * TRES list of attributes
    */
    'max'?: Array<object>;
    /**
    * TRES list of attributes
    */
    'min'?: Array<object>;
    /**
    * TRES list of attributes
    */
    'total'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "average",
            "baseName": "average",
            "type": "Array<object>"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "Array<object>"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "Array<object>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037JobStepStepTresRequested.attributeTypeMap;
    }
}

