/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Preemption settings
*/
export class Dbv0036QosPreempt {
    /**
    * List of preemptable QOS
    */
    'list'?: Array<string>;
    /**
    * List of preemption modes
    */
    'mode'?: Array<string>;
    /**
    * Grace period (s) before jobs can preempted
    */
    'exemptTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "list",
            "baseName": "list",
            "type": "Array<string>"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "Array<string>"
        },
        {
            "name": "exemptTime",
            "baseName": "exempt_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosPreempt.attributeTypeMap;
    }
}

