/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Job comments by type
*/
export class Dbv0036JobComment {
    /**
    * Administrator set comment
    */
    'administrator'?: string;
    /**
    * Job comment
    */
    'job'?: string;
    /**
    * System set comment
    */
    'system'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "administrator",
            "baseName": "administrator",
            "type": "string"
        },
        {
            "name": "job",
            "baseName": "job",
            "type": "string"
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobComment.attributeTypeMap;
    }
}

