/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0037QosLimitsMax } from './dbv0037QosLimitsMax';
import { Dbv0037QosLimitsMin } from './dbv0037QosLimitsMin';

/**
* Assigned limits
*/
export class Dbv0037QosLimits {
    'max'?: Dbv0037QosLimitsMax;
    'min'?: Dbv0037QosLimitsMin;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "max",
            "baseName": "max",
            "type": "Dbv0037QosLimitsMax"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "Dbv0037QosLimitsMin"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037QosLimits.attributeTypeMap;
    }
}

