/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036AssociationShortInfo } from './dbv0036AssociationShortInfo';
import { Dbv0036CoordinatorInfo } from './dbv0036CoordinatorInfo';

/**
* Account description
*/
export class Dbv0036Account {
    /**
    * List of assigned associations
    */
    'associations'?: Array<Dbv0036AssociationShortInfo>;
    /**
    * List of assigned coordinators
    */
    'coordinators'?: Array<Dbv0036CoordinatorInfo>;
    /**
    * Description of account
    */
    'description'?: string;
    /**
    * Name of account
    */
    'name'?: string;
    /**
    * Assigned organization of account
    */
    'organization'?: string;
    /**
    * List of properties of account
    */
    'flags'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "associations",
            "baseName": "associations",
            "type": "Array<Dbv0036AssociationShortInfo>"
        },
        {
            "name": "coordinators",
            "baseName": "coordinators",
            "type": "Array<Dbv0036CoordinatorInfo>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "string"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036Account.attributeTypeMap;
    }
}

