/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Heterogeneous Job details (optional)
*/
export class Dbv0036JobHet {
    /**
    * Parent HetJob id
    */
    'jobId'?: object;
    /**
    * Offset of this job to parent
    */
    'jobOffset'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "object"
        },
        {
            "name": "jobOffset",
            "baseName": "job_offset",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobHet.attributeTypeMap;
    }
}

