/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Limit on wallclock per settings
*/
export class Dbv0036QosLimitsMaxWallClockPer {
    /**
    * Max wallclock per QOS
    */
    'qos'?: number;
    /**
    * Max wallclock per job
    */
    'job'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "qos",
            "baseName": "qos",
            "type": "number"
        },
        {
            "name": "job",
            "baseName": "job",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosLimitsMaxWallClockPer.attributeTypeMap;
    }
}

