/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036QosLimitsMaxAccruing } from './dbv0036QosLimitsMaxAccruing';
import { Dbv0036QosLimitsMaxJobs } from './dbv0036QosLimitsMaxJobs';
import { Dbv0036QosLimitsMaxTres } from './dbv0036QosLimitsMaxTres';
import { Dbv0036QosLimitsMaxWallClock } from './dbv0036QosLimitsMaxWallClock';

/**
* Limits on max settings
*/
export class Dbv0036QosLimitsMax {
    'wallClock'?: Dbv0036QosLimitsMaxWallClock;
    'jobs'?: Dbv0036QosLimitsMaxJobs;
    'accruing'?: Dbv0036QosLimitsMaxAccruing;
    'tres'?: Dbv0036QosLimitsMaxTres;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "wallClock",
            "baseName": "wall_clock",
            "type": "Dbv0036QosLimitsMaxWallClock"
        },
        {
            "name": "jobs",
            "baseName": "jobs",
            "type": "Dbv0036QosLimitsMaxJobs"
        },
        {
            "name": "accruing",
            "baseName": "accruing",
            "type": "Dbv0036QosLimitsMaxAccruing"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "Dbv0036QosLimitsMaxTres"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosLimitsMax.attributeTypeMap;
    }
}

