/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036AssociationMaxPerAccount } from './dbv0036AssociationMaxPerAccount';

/**
* Max per settings
*/
export class Dbv0036AssociationMaxPer {
    'account'?: Dbv0036AssociationMaxPerAccount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "Dbv0036AssociationMaxPerAccount"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036AssociationMaxPer.attributeTypeMap;
    }
}

