/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* CPU frequency requested
*/
export class Dbv0036JobStepCPURequestedFrequency {
    /**
    * Min CPU frequency
    */
    'min'?: number;
    /**
    * Max CPU frequency
    */
    'max'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "min",
            "baseName": "min",
            "type": "number"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobStepCPURequestedFrequency.attributeTypeMap;
    }
}

