/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036Account } from './dbv0036Account';
import { Dbv0036Association } from './dbv0036Association';
import { Dbv0036Error } from './dbv0036Error';
import { Dbv0036Qos } from './dbv0036Qos';
import { Dbv0036User } from './dbv0036User';
import { Dbv0036Wckey } from './dbv0036Wckey';

export class Dbv0036ConfigInfo {
    /**
    * Slurm errors
    */
    'errors'?: Array<Dbv0036Error>;
    /**
    * Array of TRES
    */
    'tres'?: Array<Array<object>>;
    /**
    * Array of accounts
    */
    'accounts'?: Array<Dbv0036Account>;
    /**
    * Array of associations
    */
    'associations'?: Array<Dbv0036Association>;
    /**
    * Array of users
    */
    'users'?: Array<Dbv0036User>;
    /**
    * Array of qos
    */
    'qos'?: Array<Dbv0036Qos>;
    /**
    * Array of wckeys
    */
    'wckeys'?: Array<Dbv0036Wckey>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Dbv0036Error>"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "Array<Array<object>>"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<Dbv0036Account>"
        },
        {
            "name": "associations",
            "baseName": "associations",
            "type": "Array<Dbv0036Association>"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<Dbv0036User>"
        },
        {
            "name": "qos",
            "baseName": "qos",
            "type": "Array<Dbv0036Qos>"
        },
        {
            "name": "wckeys",
            "baseName": "wckeys",
            "type": "Array<Dbv0036Wckey>"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036ConfigInfo.attributeTypeMap;
    }
}

