/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036AssociationShortInfo } from './dbv0036AssociationShortInfo';

/**
* Assigned associations
*/
export class Dbv0036UserAssociations {
    'root'?: Dbv0036AssociationShortInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "root",
            "baseName": "root",
            "type": "Dbv0036AssociationShortInfo"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036UserAssociations.attributeTypeMap;
    }
}

