/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036Error } from './dbv0036Error';
import { Dbv0036Wckey } from './dbv0036Wckey';

export class Dbv0036WckeyInfo {
    /**
    * Slurm errors
    */
    'errors'?: Array<Dbv0036Error>;
    /**
    * List of wckeys
    */
    'wckeys'?: Array<Dbv0036Wckey>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Dbv0036Error>"
        },
        {
            "name": "wckeys",
            "baseName": "wckeys",
            "type": "Array<Dbv0036Wckey>"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036WckeyInfo.attributeTypeMap;
    }
}

