/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036JobExitCodeSignal } from './dbv0036JobExitCodeSignal';

export class Dbv0037JobExitCode {
    /**
    * Job exit status
    */
    'status'?: string;
    /**
    * Return code from parent process
    */
    'returnCode'?: number;
    'signal'?: Dbv0036JobExitCodeSignal;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "returnCode",
            "baseName": "return_code",
            "type": "number"
        },
        {
            "name": "signal",
            "baseName": "signal",
            "type": "Dbv0036JobExitCodeSignal"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0037JobExitCode.attributeTypeMap;
    }
}

