/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Rollup statistics
*/
export class Dbv0036DiagRollups {
    /**
    * Type of rollup
    */
    'type'?: string;
    /**
    * Timestamp of last rollup
    */
    'lastRun'?: number;
    /**
    * Timestamp of last cycle
    */
    'lastCycle'?: number;
    /**
    * Max time of all cycles
    */
    'maxCycle'?: number;
    /**
    * Total time (s) spent doing rollup
    */
    'totalTime'?: number;
    /**
    * Average time (s) of cycle
    */
    'meanCycles'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "lastRun",
            "baseName": "last_run",
            "type": "number"
        },
        {
            "name": "lastCycle",
            "baseName": "last_cycle",
            "type": "number"
        },
        {
            "name": "maxCycle",
            "baseName": "max_cycle",
            "type": "number"
        },
        {
            "name": "totalTime",
            "baseName": "total_time",
            "type": "number"
        },
        {
            "name": "meanCycles",
            "baseName": "mean_cycles",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036DiagRollups.attributeTypeMap;
    }
}

