/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Limits on jobs per settings
*/
export class Dbv0036QosLimitsMaxJobsPer {
    /**
    * Max jobs per account
    */
    'account'?: number;
    /**
    * Max jobs per user
    */
    'user'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "number"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosLimitsMaxJobsPer.attributeTypeMap;
    }
}

