/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036QosLimitsMaxTresMinutes } from './dbv0036QosLimitsMaxTresMinutes';
import { Dbv0036QosLimitsMaxTresPer } from './dbv0036QosLimitsMaxTresPer';

/**
* Limits on TRES
*/
export class Dbv0036QosLimitsMaxTres {
    'minutes'?: Dbv0036QosLimitsMaxTresMinutes;
    'per'?: Dbv0036QosLimitsMaxTresPer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minutes",
            "baseName": "minutes",
            "type": "Dbv0036QosLimitsMaxTresMinutes"
        },
        {
            "name": "per",
            "baseName": "per",
            "type": "Dbv0036QosLimitsMaxTresPer"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036QosLimitsMaxTres.attributeTypeMap;
    }
}

