/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dbv0036JobExitCode } from './dbv0036JobExitCode';
import { Dbv0036JobStepCPU } from './dbv0036JobStepCPU';
import { Dbv0036JobStepNodes } from './dbv0036JobStepNodes';
import { Dbv0036JobStepStatistics } from './dbv0036JobStepStatistics';
import { Dbv0036JobStepStep } from './dbv0036JobStepStep';
import { Dbv0036JobStepTasks } from './dbv0036JobStepTasks';
import { Dbv0036JobStepTime } from './dbv0036JobStepTime';

export class Dbv0036JobStep {
    'time'?: Dbv0036JobStepTime;
    'exitCode'?: Dbv0036JobExitCode;
    'nodes'?: Dbv0036JobStepNodes;
    'tasks'?: Dbv0036JobStepTasks;
    /**
    * First process PID
    */
    'pid'?: string;
    'cPU'?: Dbv0036JobStepCPU;
    /**
    * User who requested job killed
    */
    'killRequestUser'?: string;
    /**
    * State of job step
    */
    'state'?: string;
    'statistics'?: Dbv0036JobStepStatistics;
    'step'?: Dbv0036JobStepStep;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "time",
            "baseName": "time",
            "type": "Dbv0036JobStepTime"
        },
        {
            "name": "exitCode",
            "baseName": "exit_code",
            "type": "Dbv0036JobExitCode"
        },
        {
            "name": "nodes",
            "baseName": "nodes",
            "type": "Dbv0036JobStepNodes"
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Dbv0036JobStepTasks"
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "string"
        },
        {
            "name": "cPU",
            "baseName": "CPU",
            "type": "Dbv0036JobStepCPU"
        },
        {
            "name": "killRequestUser",
            "baseName": "kill_request_user",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "Dbv0036JobStepStatistics"
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "Dbv0036JobStepStep"
        }    ];

    static getAttributeTypeMap() {
        return Dbv0036JobStep.attributeTypeMap;
    }
}

