/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V0037NodeAllocation {
    /**
    * amount of assigned job memory
    */
    'memory'?: number;
    /**
    * amount of assigned job CPUs
    */
    'cpus'?: object;
    /**
    * assignment status of each socket by socket id
    */
    'sockets'?: object;
    /**
    * assignment status of each core by core id
    */
    'cores'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "memory",
            "baseName": "memory",
            "type": "number"
        },
        {
            "name": "cpus",
            "baseName": "cpus",
            "type": "object"
        },
        {
            "name": "sockets",
            "baseName": "sockets",
            "type": "object"
        },
        {
            "name": "cores",
            "baseName": "cores",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return V0037NodeAllocation.attributeTypeMap;
    }
}

