/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V0036Node {
    /**
    * computer architecture
    */
    'architecture'?: string;
    /**
    * BcastAddr
    */
    'burstbufferNetworkAddress'?: string;
    /**
    * total number of boards per node
    */
    'boards'?: number;
    /**
    * timestamp of node boot
    */
    'bootTime'?: number;
    /**
    * Arbitrary comment
    */
    'comment'?: string;
    /**
    * number of cores per socket
    */
    'cores'?: number;
    /**
    * Default task binding
    */
    'cpuBinding'?: number;
    /**
    * CPU load * 100
    */
    'cpuLoad'?: number;
    /**
    * free memory in MiB
    */
    'freeMemory'?: number;
    /**
    * configured count of cpus running on the node
    */
    'cpus'?: number;
    'features'?: string;
    /**
    * list of a node\'s available features
    */
    'activeFeatures'?: string;
    /**
    * list of a node\'s generic resources
    */
    'gres'?: string;
    /**
    * list of drained GRES
    */
    'gresDrained'?: string;
    /**
    * list of GRES in current use
    */
    'gresUsed'?: string;
    /**
    * mcs label if mcs plugin in use
    */
    'mcsLabel'?: string;
    /**
    * node name to slurm
    */
    'name'?: string;
    'nextStateAfterReboot'?: string;
    /**
    * state after reboot
    */
    'address'?: string;
    /**
    * node\'s hostname
    */
    'hostname'?: string;
    /**
    * current node state
    */
    'state'?: string;
    /**
    * operating system
    */
    'operatingSystem'?: string;
    /**
    * User allowed to use this node
    */
    'owner'?: string;
    /**
    * TCP port number of the slurmd
    */
    'port'?: number;
    /**
    * configured MB of real memory on the node
    */
    'realMemory'?: number;
    /**
    * reason for node being DOWN or DRAINING
    */
    'reason'?: string;
    /**
    * Time stamp when reason was set
    */
    'reasonChangedAt'?: number;
    /**
    * User that set the reason
    */
    'reasonSetByUser'?: string;
    /**
    * timestamp of slurmd startup
    */
    'slurmdStartTime'?: number;
    /**
    * total number of sockets per node
    */
    'sockets'?: number;
    /**
    * number of threads per core
    */
    'threads'?: number;
    /**
    * configured MB of total disk in TMP_FS
    */
    'temporaryDisk'?: number;
    /**
    * arbitrary priority of node for scheduling
    */
    'weight'?: number;
    /**
    * TRES on node
    */
    'tres'?: string;
    /**
    * Slurmd version
    */
    'slurmdVersion'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "architecture",
            "baseName": "architecture",
            "type": "string"
        },
        {
            "name": "burstbufferNetworkAddress",
            "baseName": "burstbuffer_network_address",
            "type": "string"
        },
        {
            "name": "boards",
            "baseName": "boards",
            "type": "number"
        },
        {
            "name": "bootTime",
            "baseName": "boot_time",
            "type": "number"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string"
        },
        {
            "name": "cores",
            "baseName": "cores",
            "type": "number"
        },
        {
            "name": "cpuBinding",
            "baseName": "cpu_binding",
            "type": "number"
        },
        {
            "name": "cpuLoad",
            "baseName": "cpu_load",
            "type": "number"
        },
        {
            "name": "freeMemory",
            "baseName": "free_memory",
            "type": "number"
        },
        {
            "name": "cpus",
            "baseName": "cpus",
            "type": "number"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "string"
        },
        {
            "name": "activeFeatures",
            "baseName": "active_features",
            "type": "string"
        },
        {
            "name": "gres",
            "baseName": "gres",
            "type": "string"
        },
        {
            "name": "gresDrained",
            "baseName": "gres_drained",
            "type": "string"
        },
        {
            "name": "gresUsed",
            "baseName": "gres_used",
            "type": "string"
        },
        {
            "name": "mcsLabel",
            "baseName": "mcs_label",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nextStateAfterReboot",
            "baseName": "next_state_after_reboot",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "hostname",
            "baseName": "hostname",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "operatingSystem",
            "baseName": "operating_system",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "realMemory",
            "baseName": "real_memory",
            "type": "number"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "reasonChangedAt",
            "baseName": "reason_changed_at",
            "type": "number"
        },
        {
            "name": "reasonSetByUser",
            "baseName": "reason_set_by_user",
            "type": "string"
        },
        {
            "name": "slurmdStartTime",
            "baseName": "slurmd_start_time",
            "type": "number"
        },
        {
            "name": "sockets",
            "baseName": "sockets",
            "type": "number"
        },
        {
            "name": "threads",
            "baseName": "threads",
            "type": "number"
        },
        {
            "name": "temporaryDisk",
            "baseName": "temporary_disk",
            "type": "number"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "string"
        },
        {
            "name": "slurmdVersion",
            "baseName": "slurmd_version",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0036Node.attributeTypeMap;
    }
}

