/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V0037Error } from './v0037Error';
import { V0037Ping } from './v0037Ping';

export class V0037Pings {
    /**
    * slurm errors
    */
    'errors'?: Array<V0037Error>;
    /**
    * slurm controller pings
    */
    'pings'?: Array<V0037Ping>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<V0037Error>"
        },
        {
            "name": "pings",
            "baseName": "pings",
            "type": "Array<V0037Ping>"
        }    ];

    static getAttributeTypeMap() {
        return V0037Pings.attributeTypeMap;
    }
}

