/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V0037ReservationPurgeCompleted } from './v0037ReservationPurgeCompleted';

export class V0037Reservation {
    /**
    * Allowed accounts
    */
    'accounts'?: string;
    /**
    * Reserved burst buffer
    */
    'burstBuffer'?: string;
    /**
    * Number of reserved cores
    */
    'coreCount'?: number;
    /**
    * Number of reserved specialized cores
    */
    'coreSpecCnt'?: number;
    /**
    * End time of the reservation
    */
    'endTime'?: number;
    /**
    * List of features
    */
    'features'?: string;
    /**
    * Reservation options
    */
    'flags'?: Array<string>;
    /**
    * List of groups permitted to use the reserved nodes
    */
    'groups'?: string;
    /**
    * List of licenses
    */
    'licenses'?: string;
    /**
    * Maximum delay in which jobs outside of the reservation will be permitted to overlap once any jobs are queued for the reservation
    */
    'maxStartDelay'?: number;
    /**
    * Reservationn name
    */
    'name'?: string;
    /**
    * Count of nodes reserved
    */
    'nodeCount'?: number;
    /**
    * List of reserved nodes
    */
    'nodeList'?: string;
    /**
    * Partition
    */
    'partition'?: string;
    'purgeCompleted'?: V0037ReservationPurgeCompleted;
    /**
    * Start time of reservation
    */
    'startTime'?: number;
    /**
    * amount of power to reserve in watts
    */
    'watts'?: number;
    /**
    * List of TRES
    */
    'tres'?: string;
    /**
    * List of users
    */
    'users'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "string"
        },
        {
            "name": "burstBuffer",
            "baseName": "burst_buffer",
            "type": "string"
        },
        {
            "name": "coreCount",
            "baseName": "core_count",
            "type": "number"
        },
        {
            "name": "coreSpecCnt",
            "baseName": "core_spec_cnt",
            "type": "number"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "string"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Array<string>"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "string"
        },
        {
            "name": "licenses",
            "baseName": "licenses",
            "type": "string"
        },
        {
            "name": "maxStartDelay",
            "baseName": "max_start_delay",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nodeCount",
            "baseName": "node_count",
            "type": "number"
        },
        {
            "name": "nodeList",
            "baseName": "node_list",
            "type": "string"
        },
        {
            "name": "partition",
            "baseName": "partition",
            "type": "string"
        },
        {
            "name": "purgeCompleted",
            "baseName": "purge_completed",
            "type": "V0037ReservationPurgeCompleted"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "watts",
            "baseName": "watts",
            "type": "number"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "string"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0037Reservation.attributeTypeMap;
    }
}

