/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V0037Partition {
    /**
    * partition options
    */
    'flags'?: Array<string>;
    /**
    * preemption type
    */
    'preemptionMode'?: Array<string>;
    /**
    * list names of allowed allocating nodes
    */
    'allowedAllocationNodes'?: string;
    /**
    * comma delimited list of accounts
    */
    'allowedAccounts'?: string;
    /**
    * comma delimited list of groups
    */
    'allowedGroups'?: string;
    /**
    * comma delimited list of qos
    */
    'allowedQos'?: string;
    /**
    * name of alternate partition
    */
    'alternative'?: string;
    /**
    * TRES billing weights
    */
    'billingWeights'?: string;
    /**
    * default MB memory per allocated CPU
    */
    'defaultMemoryPerCpu'?: number;
    /**
    * default time limit (minutes)
    */
    'defaultTimeLimit'?: number;
    /**
    * comma delimited list of denied accounts
    */
    'deniedAccounts'?: string;
    /**
    * comma delimited list of denied qos
    */
    'deniedQos'?: string;
    /**
    * preemption grace time (seconds)
    */
    'preemptionGraceTime'?: number;
    /**
    * maximum allocated CPUs per node
    */
    'maximumCpusPerNode'?: number;
    /**
    * maximum memory per allocated CPU (MiB)
    */
    'maximumMemoryPerNode'?: number;
    /**
    * Max nodes per job
    */
    'maximumNodesPerJob'?: number;
    /**
    * Max time limit per job
    */
    'maxTimeLimit'?: number;
    /**
    * Min number of nodes per job
    */
    'minNodesPerJob'?: number;
    /**
    * Partition name
    */
    'name'?: string;
    /**
    * list names of nodes in partition
    */
    'nodes'?: string;
    /**
    * job\'s time limit can be exceeded by this number of minutes before cancellation
    */
    'overTimeLimit'?: number;
    /**
    * job priority weight factor
    */
    'priorityJobFactor'?: number;
    /**
    * tier for scheduling and preemption
    */
    'priorityTier'?: number;
    /**
    * partition QOS name
    */
    'qos'?: string;
    /**
    * Partition state
    */
    'state'?: string;
    /**
    * Total cpus in partition
    */
    'totalCpus'?: number;
    /**
    * Total number of nodes in partition
    */
    'totalNodes'?: number;
    /**
    * configured TRES in partition
    */
    'tres'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Array<string>"
        },
        {
            "name": "preemptionMode",
            "baseName": "preemption_mode",
            "type": "Array<string>"
        },
        {
            "name": "allowedAllocationNodes",
            "baseName": "allowed_allocation_nodes",
            "type": "string"
        },
        {
            "name": "allowedAccounts",
            "baseName": "allowed_accounts",
            "type": "string"
        },
        {
            "name": "allowedGroups",
            "baseName": "allowed_groups",
            "type": "string"
        },
        {
            "name": "allowedQos",
            "baseName": "allowed_qos",
            "type": "string"
        },
        {
            "name": "alternative",
            "baseName": "alternative",
            "type": "string"
        },
        {
            "name": "billingWeights",
            "baseName": "billing_weights",
            "type": "string"
        },
        {
            "name": "defaultMemoryPerCpu",
            "baseName": "default_memory_per_cpu",
            "type": "number"
        },
        {
            "name": "defaultTimeLimit",
            "baseName": "default_time_limit",
            "type": "number"
        },
        {
            "name": "deniedAccounts",
            "baseName": "denied_accounts",
            "type": "string"
        },
        {
            "name": "deniedQos",
            "baseName": "denied_qos",
            "type": "string"
        },
        {
            "name": "preemptionGraceTime",
            "baseName": "preemption_grace_time",
            "type": "number"
        },
        {
            "name": "maximumCpusPerNode",
            "baseName": "maximum_cpus_per_node",
            "type": "number"
        },
        {
            "name": "maximumMemoryPerNode",
            "baseName": "maximum_memory_per_node",
            "type": "number"
        },
        {
            "name": "maximumNodesPerJob",
            "baseName": "maximum_nodes_per_job",
            "type": "number"
        },
        {
            "name": "maxTimeLimit",
            "baseName": "max_time_limit",
            "type": "number"
        },
        {
            "name": "minNodesPerJob",
            "baseName": "min_nodes_per_job",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nodes",
            "baseName": "nodes",
            "type": "string"
        },
        {
            "name": "overTimeLimit",
            "baseName": "over_time_limit",
            "type": "number"
        },
        {
            "name": "priorityJobFactor",
            "baseName": "priority_job_factor",
            "type": "number"
        },
        {
            "name": "priorityTier",
            "baseName": "priority_tier",
            "type": "number"
        },
        {
            "name": "qos",
            "baseName": "qos",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "totalCpus",
            "baseName": "total_cpus",
            "type": "number"
        },
        {
            "name": "totalNodes",
            "baseName": "total_nodes",
            "type": "number"
        },
        {
            "name": "tres",
            "baseName": "tres",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V0037Partition.attributeTypeMap;
    }
}

