/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* POSIX signal name
*/
export enum V0036Signal {
    Hup = <any> 'HUP',
    Int = <any> 'INT',
    Quit = <any> 'QUIT',
    Abrt = <any> 'ABRT',
    Kill = <any> 'KILL',
    Alrm = <any> 'ALRM',
    Term = <any> 'TERM',
    Usr1 = <any> 'USR1',
    Usr2 = <any> 'USR2',
    Urg = <any> 'URG',
    Cont = <any> 'CONT',
    Stop = <any> 'STOP',
    Tstp = <any> 'TSTP',
    Ttin = <any> 'TTIN',
    Ttou = <any> 'TTOU'
}
