/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V0037DiagStatistics } from './v0037DiagStatistics';
import { V0037Error } from './v0037Error';

export class V0037Diag {
    /**
    * slurm errors
    */
    'errors'?: Array<V0037Error>;
    'statistics'?: V0037DiagStatistics;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<V0037Error>"
        },
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "V0037DiagStatistics"
        }    ];

    static getAttributeTypeMap() {
        return V0037Diag.attributeTypeMap;
    }
}

