/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V0036NodeAllocation } from './v0036NodeAllocation';

export class V0036JobResources {
    /**
    * list of assigned job nodes
    */
    'nodes'?: string;
    /**
    * number of assigned job cpus
    */
    'allocatedCpus'?: number;
    /**
    * number of assigned job hosts
    */
    'allocatedHosts'?: number;
    /**
    * node allocations
    */
    'allocatedNodes'?: Array<V0036NodeAllocation>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nodes",
            "baseName": "nodes",
            "type": "string"
        },
        {
            "name": "allocatedCpus",
            "baseName": "allocated_cpus",
            "type": "number"
        },
        {
            "name": "allocatedHosts",
            "baseName": "allocated_hosts",
            "type": "number"
        },
        {
            "name": "allocatedNodes",
            "baseName": "allocated_nodes",
            "type": "Array<V0036NodeAllocation>"
        }    ];

    static getAttributeTypeMap() {
        return V0036JobResources.attributeTypeMap;
    }
}

