/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V0037Error {
    /**
    * error message
    */
    'error'?: string;
    /**
    * error number
    */
    'errno'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "errno",
            "baseName": "errno",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V0037Error.attributeTypeMap;
    }
}

