/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V0036Ping {
    /**
    * slurm controller hostname
    */
    'hostname'?: string;
    /**
    * slurm controller host up
    */
    'ping'?: V0036Ping.PingEnum;
    /**
    * slurm controller mode
    */
    'mode'?: string;
    /**
    * slurm controller status
    */
    'status'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hostname",
            "baseName": "hostname",
            "type": "string"
        },
        {
            "name": "ping",
            "baseName": "ping",
            "type": "V0036Ping.PingEnum"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return V0036Ping.attributeTypeMap;
    }
}

export namespace V0036Ping {
    export enum PingEnum {
        Up = <any> 'UP',
        Down = <any> 'DOWN'
    }
}
